language: node_js
node_js:
- '0.11'
- '0.10'
notifications:
  slack:
    secure: PHQSJmO6bPXVVY3PI+ptdyBkM7lXPTstaB6wzoWSDlkV8bktguoVobWCk484eS0Tirt5XlZIc42XkwE8g3Nvlg+fj8XJ+kJRjIi5EjKKOAwWBg8x0Fls4HJA7wsHRYF+J/NpkFsDKAwo3goPqZyE/HzQkUoVc5fouJ7REzOoDAl1FBgO2BLmcnUP4EqX2VS6V8jeE4uIKZEI6rFHsI6NR6TfvtZpfcD0N3PHYiRq1k2D6379rIe659Mpf4dHrMJOB1Ua6temFJlbxQzXh8zIlJnalvMWkBUfS5gEi0MYNHfAtCCG4ce756n4ugdD6us4gbMsC/xSV1sY+Xk+FbSjZRP0cYx1vtPGAXCLfwt1g84ZCPRB/8wisNMOwgG5YptnuOSp0eCcBeK75bDoca3ARXmqbiuw8V7rBqBfvLIPS5n6YzTmAwxT1tJxWpY2hm8ZWjA8Fm0fVlarJ7HtzV8/tBgLzI8CyUOmvz0mBhjnXOWUCJL0U70G2qbNg04dWDf3QTybKLMfcJVxltIyKIFnXA97e7MtH7tmTQTc0+iT6xYMMqF1dPww+2gLOdNLNA0MMQI3aF+FlqUrQ0c7srS9e0pnGPy2V9ZUZ52vx2xLnv36qCO+DcRIz0lcTy/Z4Dtmb+wqah0+R0n6ta0+8cTlPxQpVg/vQNw6fehgUmQJlkI=
